In [1]:
# Use the following code for the questions below:
import numpy as np


a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


# How many negative numbers are there?
my_negative_mask = a < 0
len(a[my_negative_mask])




4

In [2]:
import numpy as np


a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

# How many positive numbers are there?
my_positive_mask = a > 0
len(a[my_positive_mask])


5

In [3]:
import numpy as np


a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

# How many even positive numbers are there?
my_positive_mask = a > 0
len(a[my_positive_mask % 2 == 0])

7

In [4]:
import numpy as np


a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

# if you were to add 3 to each data point, how many positive numbers would there be?
add_three_mask = a + 3
len(a[add_three_mask > 0])


10

In [6]:
import numpy as np


a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

# If you squared each number, what would the new mean and standard deviation be?
squared_mask = a ** 2
print(squared_mask.mean())
print(squared_mask.std())



74.0
144.0243035046516


In [8]:
import numpy as np


a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

# A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.
mean_mask = a.mean()
a - mean_mask


array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [9]:
import numpy as np


a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

# Calculate the z-score for each data point. Recall that the z-score is given by:
from scipy import stats

stats.zscore(a, axis=None)


array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [11]:
import numpy as np
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(a)

In [12]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)

In [13]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)

In [18]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
meean_of_a = sum(a) / len(a)

In [116]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = 1
for num in a:
    product_of_a *= num
print(product_of_a)

3628800


In [117]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = [num ** 2 for num in a]
print(squares_of_a)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [118]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = [num for num in a if num % 2 != 0]
print(odds_in_a)

[1, 3, 5, 7, 9]


In [119]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = [num for num in a if num % 2 == 0]
print(evens_in_a)

[2, 4, 6, 8, 10]


In [120]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
import numpy as np

b = np.array(range(1,101))
sum_of_b = 0
for row in b:
    sum_of_b += row.sum()

In [158]:
# Exercise 2 - refactor the following to use numpy. 
import numpy as np

# min_of_b = b[0].min() if b[0].min() <= b[1].min() else b[1].min()  
b.min()


1

In [159]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
# max_of_b = b[0].max() if b[0].max() >= b[1].max() else b[1].max()
b.max()


6

In [160]:

# Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = b[0].sum() + b[1].sum() / b[0].shape + b[1].shape
b.mean()

3.5

In [124]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
b = np.array(range(1,101))
product = np.prod(np.array(b))
# product_of_b = 1
# for row in b:
    #for number in row:
        #product_of_b *= number


In [125]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
# squares_of_b = []
# for row in b:
    # for number in row:
        # squares_of_b.append(number**2)
b = np.array(range(1,101))
sqaures_of_b = np.square(np.array(b))

In [126]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
# odds_in_b = []
# for row in b:
    # for number in row:
        # if(number % 2 != 0):
            # odds_in_b.append(number)
odds_mask = b % 2 != 0
b[odds_mask]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [127]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
# evens_in_b = []
# for row in b:
    # for number in row:
        # if(number % 2 == 0):
            # evens_in_b.append(number)
evens_mask = b % 2 == 0
b[evens_mask]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [128]:
# Exercise 9 - print out the shape of the array b.
b.shape

(100,)

In [129]:
# Exercise 10 - transpose the array b.
np.transpose(b)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [130]:
list(b)

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [131]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b = np.array(range(1,7))
reshaped = b.reshape(1, 6)
print(reshaped)

[[1 2 3 4 5 6]]


In [132]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
reshaped_2 = b.reshape(6, 1)
print(reshaped_2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [133]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
c = np.array(c)
print(c.min())
print(c.max())
print(sum(c))
print(np.prod(c))

1
9
[12 15 18]
362880


In [134]:
# Exercise 2 - Determine the standard deviation of c.
c.std()

2.581988897471611

In [135]:
# Exercise 3 - Determine the variance of c.
c.var()

6.666666666666667

In [136]:
# Exercise 4 - Print out the shape of the array c
c.shape

(3, 3)

In [137]:
# Exercise 5 - Transpose c and print out transposed result.
print(c.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [162]:
# Exercise 6 - Get the dot product of the array c with c. 
print(np.dot(c,c))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [139]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
almost = sum(c.transpose() * c)
print(sum(almost))

261


In [140]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
lol = c.transpose()
print(np.prod(c * lol))

131681894400


In [141]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [142]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [143]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [144]:
# Exercise 4 - Find all the negative numbers in d
d = np.array(d)
negative_mask = d < 0
d[negative_mask]

array([-90, -30, -45, -45])

In [145]:
# Exercise 5 - Find all the positive numbers in d
positive_mask = d > 0
d[positive_mask]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [146]:
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [166]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(d))

11

In [148]:
d.shape

(3, 6)

In [156]:
# Exercise 9 - Transpose and then print out the shape of d.
dtr = d.transpose()
print(dtr.shape)

(6, 3)


In [157]:
# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])